# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86a05ecd6951ec07c81923a4a892772e21380642e0ef4b0b11f3aae46c18b10b370f25416eef8ee1fc570fdbb57cb650db4aa7bd9d1b89f48279e989f0c454c8

test:
  secret_key_base: 6ead16bcc2f28f28f9141ec2c6e73f402eed3669c5a5ccc5d92ea5903d6c8f53993a634cd1a42f508f98ff18973b737825aa66ee38f4113621e03d5f46547c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
